apiVersion: v1
kind: Service
metadata:
  name: kubeovn-perfservice
  namespace: kube-system
  labels:
    app: kubeovn-perfserver
spec:
  selector:
    app: kubeovn-perfserver
  ports:
    - port: 11111
      targetPort: 11111