apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubeovn-perfmonitor
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: kubeovn-perfmonitor
    spec:
      containers:
        - name: kubeovn-perfmonitor
          image: kubeovn/perf:v0.1
          imagePullPolicy: Always
          command:
            - python3
            - /startMonit.py
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: SERVER
              value: "SETSERVER"
            - name: PORT
              value: "11111"
            - name: TIME
              value: "SETTIME"
            - name: DURATION
              value: "60"
            - name: STEP
              value: "5"
          securityContext:
            privileged: true
            runAsUser: 0
      restartPolicy: Always
      nodeSelector:
        perf-monitor: 'yes'
      hostNetwork: true
      hostPID: true
  selector:
    matchLabels:
      app: kubeovn-perfmonitor
